import { Inject, Injectable } from "@nestjs/common";
import { SUBMISSION_REPOSITORY, SubmissionRepository } from "../../../domain/repositories/submission.repository";
import { Submission } from "../../../domain/entities/submission.entity";
import { SubmissionStatus } from "../../../domain/enums/submission-status.enum";
import { SUBMISSION_QUEUE, SubmissionQueue } from "../../ports/submission-queue.port";

@Injectable()
export class CreateSubmissionUseCase {
  constructor(
    @Inject(SUBMISSION_REPOSITORY)
    private readonly submissionRepo: SubmissionRepository,
    @Inject(SUBMISSION_QUEUE)
    private readonly submissionQueue: SubmissionQueue,
  ) {}

  async execute(studentId: number, challengeId: number, sql: string) {
    const submission = new Submission(
      null,              // id (autogenerated)
      studentId,
      challengeId,
      null,              // evaluationId
      'postgresql',      // engine
      sql,
      SubmissionStatus.QUEUED,
      new Date(),
    );

    const saved = await this.submissionRepo.save(submission);
    await this.submissionQueue.enqueue(saved.id, sql);

    return saved;
  }
}
